//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Infrastructure.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   &lt;value&gt;&quot;PROVIDER=SQLOLEDB;SERVER=192.168.44.155\SQLEXPRESS;DATABASE=accounting_process;user id=sa;password=sqlserver&quot;&lt;/value&gt; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DATABASECONNECTIONSTRING {
            get {
                return ResourceManager.GetString("DATABASECONNECTIONSTRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   excel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExcelWorkbookPassword {
            get {
                return ResourceManager.GetString("ExcelWorkbookPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   .\logs\ExceptionLogs.txt に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LogFilePath {
            get {
                return ResourceManager.GetString("LogFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   AccountingProcessFile.xlsx に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SaveFile {
            get {
                return ResourceManager.GetString("SaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   .\files\ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SaveFolderPath {
            get {
                return ResourceManager.GetString("SaveFolderPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   経理データ出力 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SheetName {
            get {
                return ResourceManager.GetString("SheetName", resourceCulture);
            }
        }
    }
}
